# Generated by Django 3.1.6 on 2021-02-02 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210202_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.BigIntegerField(validators=[django.core.validators.MaxLengthValidator(14), django.core.validators.MinLengthValidator(14)]),
        ),
    ]
