# Generated by Django 3.1.6 on 2021-02-02 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210203_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(db_index=True, max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Number of length 3', regex='^[0-9]{3,3}$')]),
        ),
    ]
