# Generated by Django 3.1.6 on 2021-02-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20210203_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_no', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
    ]
