# Generated by Django 3.1.6 on 2021-02-03 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20210203_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Number of length 3', regex='^[0-9]{1,3}$')])),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.allcourses')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
